@echo off
echo Starting Redis on port 6382...
start "" redis-server --port 6382
echo Waiting for Redis to start...
timeout /t 3 /nobreak
echo Syncing data to Redis...
python -m flask --app config:create_app sync-to-redis
echo Sync completed.